// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="">
//         {/* <Navbar /> */}
//         <main className="">{children}</main>
//         {/* <Footer /> */}
//       </body>
//     </html>
//   );
// }

// components/Layout.tsx
import React, { ReactNode } from 'react';
import  "./globals.css";
import Navbar from './components/Navbar';
import Footer from './components/Footer';
type LayoutProps = {
  children: ReactNode;
};

const Layout = ({ children }: LayoutProps) => {
  return (
    <html>
      <body>
        <div >
          <Navbar />
          <main className="bodyContent">
            {children}
          </main>
          
          <Footer />
      
        </div>
      </body>
    </html>
  );
};

export default Layout;
